%YAML 1.2
---
imports:
  - resource: secret_parameters.yml
  - resource: parameters.yml
  - resource: ../package.json
    pick:
        name: app.name
        version: app.version
  - resource: ../config.json

app:
  sid: istex-jobs
  configPath: ./config.json
  doExitOnUnhandledRejection: true

tasks:
    generateHoldings:
        institutionalLinksPath: institutional_links_istex.xml
        corpusBlackList: %ISTEX_JOBS_HOLDINGS_CORPUS_BLACKLIST%

security:
  reverseProxy: %env(ISTEX_JOBS_REVERSE_PROXY)%

istex:
  api:
    retry: 5
    url: %env(ISTEX_JOBS_ISTEX_API_URL)%

    # Boolean This should stay disabled when making requests to internal hostnames, @see https://www.npmjs.com/package/got#dnscache
    useCacheLookup: %env(ISTEX_JOBS_USE_CACHE_LOOKUP)%

    # timeout may be Object or Number, @see https://www.npmjs.com/package/got#timeout
    timeout:
     response: 20000 # ms

  review:
    retry: 5
    url: %env(ISTEX_JOBS_REVIEW_URL)%
    # timeout may be Object or Number, @see https://www.npmjs.com/package/got#timeout
    timeout:
     socket: 60000
     response: 30000 # ms

exchange:
    outputPath: ./output/exchange

nodeMailer:
   useEthereal: false
   transports:
        default:
            host: %env(ISTEX_JOBS_MAILER_HOST)%
            port: %env(ISTEX_JOBS_MAILER_PORT)%
   onErrorTo: %env(ISTEX_JOBS_MAILER_TO)%


log:
  path: %env(ISTEX_JOBS_LOG_PATH)%

express:
  api:
    host: %env(ISTEX_JOBS_API_HOST)%
    port: %env(ISTEX_JOBS_API_PORT)%
  allowedAccessMethods:
    - GET
    - OPTIONS

nodejs:
  stackTraceLimit: 40
