%YAML 1.2
---
parameters:
  ISTEX_JOBS_USE_CACHE_LOOKUP: false
  ISTEX_JOBS_ISTEX_API_URL: https://api.istex.fr
  ISTEX_JOBS_REVIEW_URL: https://revue-sommaire.data.istex.fr
  ISTEX_JOBS_API_HOST: 0.0.0.0
  ISTEX_JOBS_API_PORT: 8080
  ISTEX_JOBS_LOG_PATH: /var/log
  ISTEX_JOBS_REVERSE_PROXY: false
  ISTEX_JOBS_HOLDINGS_CORPUS_BLACKLIST: ~
