'use strict';

module.exports = {
  corpusTypes: {
    acs: 'journals',
    wiley: 'journals',
    elsevier: 'journals',
    'springer-journals': 'journals',
    oup: 'journals',
    'springer-ebooks': 'ebooks',
    cambridge: 'journals',
    sage: 'journals',
    bmj: 'journals',
    iop: 'journals',
    nature: 'journals',
    'rsc-journals': 'journals',
    'degruyter-journals': 'journals',
    'edp-sciences': 'journals',
    emerald: 'journals',
    'brill-journals': 'journals',
    rsl: 'journals',
    'brepols-journals': 'journals',
    'rsc-ebooks': 'ebooks',
    'open-edition-ebooks': 'ebooks',
    droz: 'ebooks',
    lavoisier: 'journals',
    'brepols-ebooks': 'ebooks',
    'brill-hacco': 'ebooks',
    gsl: 'ebooks',
    duke: 'journals',
    'taylor-francis': 'ebooks',
    'numerique-premium': 'ebooks',
    ecco: 'ebooks',
    eebo: 'ebooks',
  },
};
